"""
This is a setup.py script generated by py2app.

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['chrono.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': False,
    'plist': {
        'LSUIElement': True,
        'CFBundleName': 'Chrono',
        'CFBundleDisplayName': 'Chrono',
        'CFBundleIdentifier': 'com.user.chrono',
        'CFBundleVersion': '1.0',
        'CFBundleShortVersionString': '1.0',
        'LSMinimumSystemVersion': '10.15',
        'NSHighResolutionCapable': True,
    },
    'packages': ['rumps'],
    'includes': ['rumps', 'AppKit', 'Foundation'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
